FROM mcr.microsoft.com/mirror/docker/library/ubuntu:22.04 AS base

ENV DEBIAN_FRONTEND=noninteractive
RUN echo "base"

# Copy the marketplace image build script and build package and run it with tests
FROM base AS add_project
WORKDIR /opt/cycle
ADD . /opt/cycle/cyclecloud-marketplace-image
WORKDIR /opt/cycle/cyclecloud-marketplace-image
RUN echo "add_project"

# Install required tools and dependencies
FROM add_project AS install_deps
RUN chmod +x /opt/cycle/cyclecloud-marketplace-image/install-dep.sh
RUN /opt/cycle/cyclecloud-marketplace-image/install-dep.sh
RUN echo "install_deps"

FROM install_deps AS build_image
RUN chmod +x /opt/cycle/cyclecloud-marketplace-image/build_image.sh && \
    /opt/cycle/cyclecloud-marketplace-image/build_image.sh && \
   echo "build_image"

FROM install_deps AS run_test_on_existing_image
ARG OS_IMAGE_RESOURCE_ID
RUN /opt/cycle/cyclecloud-marketplace-image/test_cc_image.sh ${OS_IMAGE_RESOURCE_ID} && \
   echo "run_test_on_existing_image"

CMD ["/bin/bash"]